### ISSUE TITLE
Bug: Mac OS Scrollbar looks wrong when hovered

### ISSUE THREAD

**Issue by chrisgrieser** [mgmeyers/obsidian-native-scrollbars#1] opened 2021-12-26 19:37 UTC
a hovered + active scrollbar in mac OS seems to look wrong. Can reproduce in help vault as well.

https://user-images.githubusercontent.com/73286100/147418335-07861bd6-02ff-46da-9d23-d5dd731d7ae0.mov

**Comment by mgmeyers** [comment] 2021-12-26 19:52
Hmm, yes, I see this, too. I don't think the issue is with this plugin, but rather how macOS determines the scrollbar background.

https://stackoverflow.com/questions/21157231/mac-os-x-scrollbar-is-sometimes-white-transparent-and-sometimes-black-transpare

Trying to figure out a solution now...

**Comment by mgmeyers** [comment] 2021-12-26 20:07
Here's a demo of the problem: https://codepen.io/mgmeyers/pen/KKXyjYv

It seems that the scrollbar background color is determined by the background color of the scroll container.

**Comment by mgmeyers** [comment] 2021-12-26 20:39
So far, the only solution I've found is to set the background color of the scroll container 🤔

**Comment by mgmeyers** [comment] 2021-12-27 18:27
@chrisgrieser After quite a bit of testing and searching, the only solution I could find is to set the background color of the scroll container. MacOS will the determine the appropriate scrollbar theme. If the background is transparent, it seems to default to the light theme. I've found that setting a nearly transparent background works, eg `background-color: #00000001;`.

This seems to be an issue with either macOS or webkit, so I'm going to close this. I'll add some info to the readme about this, though.

**Closed as completed by mgmeyers** 2021-12-27 18:27 UTC
Labels: help wanted

**Comment by mgmeyers** [comment] 2021-12-27 19:18
Here's how I handled this in California Coast:

https://github.com/mgmeyers/obsidian-california-coast-theme/blob/main/src/plugins/native-scrollbars.scss
